# Copyright (c) 2021 Luca Cappa
# Released under the term specified in file LICENSE.txt
# SPDX short identifier: MIT
#
# The peculiarity of this workflow is that assumes vcpkg stored as a submodule of this repository.
# This workflow does the following:
# - Restores vcpkg artifacts from cache.
# - Sets up vcpkg if needed, then run CMake with CMakePreset.json using a configuration
#   that leverages the vcpkg's toolchain file. This will automatically run vcpkg to install dependencies
#   described by the vcpkg.json manifest file. It will be a no-op if those are restored from cache.
# - Finally builds the sources with Ninja.
name: build
on: [push, workflow_dispatch]

jobs:
  VCPKG:
    name: ${{ matrix.os }}-${{ github.workflow }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-2022]
        os: [macos-10.15]
        include:
          # - os: 'ubuntu-latest'
          #   mono: 'mono'
          #   triplet: 'x64-linux'
          #   artifact: 'x86_64-linux'
          #   exe_ext: ''
          #   build_dir: ninja-vcpkg
          # - os: 'windows-2022'
          #   mono: ''
          #   triplet: 'x64-win'
          #   artifact: 'x86_64-windows'
          #   exe_ext: '.exe'
          #   build_dir: vs-vcpkg
          - os: 'macos-10.15'
          #  os: 'macos-latest'
            mono: 'mono'
            triplet: 'x64-osx'
            artifact: 'x86_64-macos'
            exe_ext: ''
            build_dir: ninja-vcpkg

    env:
      VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub,readwrite'

    steps:
      - name: 'Remove old VCPKG'
        if: startsWith(matrix.os, 'ubuntu') || startsWith(matrix.os, 'macOS')
        shell: 'bash'
        run: sudo rm -rf "$VCPKG_INSTALLATION_ROOT"

      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: seanmiddleditch/gha-setup-ninja@master

      - uses: lukka/get-cmake@latest

      - name: 'Bootstrap VCPKG'
        shell: bash
        run: vcpkg/bootstrap-vcpkg.sh

      - name: 'Setup NuGet Credentials'
        shell: 'bash'
        run: >
          ${{ matrix.mono }} `./vcpkg/vcpkg fetch nuget | tail -n 1`
          sources add
          -source "https://nuget.pkg.github.com/free-audio/index.json"
          -storepasswordincleartext
          -name "GitHub"
          -username "free-audio"
          -password "${{ secrets.GITHUB_TOKEN }}"

      - name: Setup MacOS
        if: startsWith(matrix.os, 'macOS')
        run: brew install automake autoconf ninja cmake

      - name: Setup Ubuntu
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo apt update && sudo apt upgrade && sudo apt install
          build-essential gperf ninja-build cmake
          libgl1-mesa-dev
          libfontconfig1-dev
          libfreetype6-dev
          libx11-dev
          libx11-xcb-dev
          libxcb-damage0-dev
          libxcb-dpms0-dev
          libxcb-glx0-dev
          libxcb-icccm4-dev
          libxcb-image0-dev
          libxcb-keysyms1-dev
          libxcb-present-dev
          libxcb-randr0-dev
          libxcb-record0-dev
          libxcb-render-util0-dev
          libxcb-render0-dev
          libxcb-res0-dev
          libxcb-shape0-dev
          libxcb-shm0-dev
          libxcb-sync-dev
          libxcb-util-dev
          libxcb-xfixes0-dev
          libxcb-xinerama0-dev
          libxcb-xkb-dev
          libxcb1-dev
          libxext-dev
          libxfixes-dev
          libxi-dev
          libxkbcommon-dev
          libxkbcommon-x11-dev
          libxrender-dev
          libatspi2.0-dev

      - name: Build
        shell: bash
        run: scripts/build.sh ${{ matrix.triplet }}

      - name: Archive artifact
        shell: bash
        run: tar -cvJf clap-host.tar.xz --strip-components 4 builds/${{matrix.build_dir}}/host/Release/clap-host${{matrix.exe_ext}}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: clap-host-${{ matrix.artifact }}.tar.xz
          path: clap-host.tar.xz
